
steps:
- name: 'gcr.io/cloud-builders/gcloud'
  id: Update staging server
  entrypoint: /bin/sh
  args:
  - '-c'
  - |
          set -x && \
          gcloud compute ssh --zone "us-central1-a" "nhrbox"  --project "aerial-studio-316704" --command='sudo -u nhr /bin/bash /home/nhr/pull.sh'
